title: ronin48llc Blog
description: Tech blog
baseurl: ""
url: "https://ronin48llc.github.io"

theme: minima

permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
